// export const SERVER_URL = 'http://localhost:3010/monitor-server'
export const SERVER_URL = 'http://47.129.235.187/monitor-server'
export const urls = {
  getServices: () => `${SERVER_URL}/services`,
  getServerStatus: () => `${SERVER_URL}/server-status`,
  getTotalRequest: () => `${SERVER_URL}/request`,
  getCpuUsage: () => `${SERVER_URL}/cpu-usage`,
  getMemUsage: () => `${SERVER_URL}/mem-usage`,
  getAvgResponse: () => `${SERVER_URL}/avg-response`,
  getResponseTimeDistribution: () => `${SERVER_URL}/dist-response`,
  getServerTimeline: () => `${SERVER_URL}/server-timeline`,
  getMachines: service => `${SERVER_URL}/machines?service=${service}`,
  getPaths: service => `${SERVER_URL}/path?service=${service}`,
  getErrorRate: service => `${SERVER_URL}/error-req?service=${service}`,
  getErrorRanking: service => `${SERVER_URL}/error-ranking?service=${service}`,
  getRxNetworkUsage: () => `${SERVER_URL}/rx-network-usage`,
  getTxNetworkUsage: () => `${SERVER_URL}/tx-network-usage`,
  getAlertRules: () => `${SERVER_URL}/alert-rules`,
  createAlertRule: () => `${SERVER_URL}/create-alert`,
  createRecipient: () => `${SERVER_URL}/create-recipient`,
  addRecipientToGroup: () => `${SERVER_URL}/add-recipient-to-group`,
  enableRule: ruleId => `${SERVER_URL}/enable-rule?ruleId=${ruleId}`,
  disableRule: ruleId => `${SERVER_URL}/disable-rule?ruleId=${ruleId}`,
  deleteRule: ruleId => `${SERVER_URL}/delete-rule?ruleId=${ruleId}`,
  updateRule: () => `${SERVER_URL}/update-rule`,
  getRecipient: () => `${SERVER_URL}/recipients`,
  removeRecipientFromGroup: () => `${SERVER_URL}/remove-recipient-from-group`,
  deleteRecipient: recipientId =>
    `${SERVER_URL}/delete-recipient?recipientId=${recipientId}`,
  getController: service => `${SERVER_URL}/controllers?service=${service}`,
  getRequestErrorRatio: () => `${SERVER_URL}/request-error-ratio`,
  getAlertType: () => `${SERVER_URL}/alert-type`,
  getGroups: () => `${SERVER_URL}/groups`,
  removeGroupFromRule: () => `${SERVER_URL}/remove-group-from-rule`,
  addGroupToRule: () => `${SERVER_URL}/add-group-to-rule`,
  updateGroupOfRule: () => `${SERVER_URL}/update-group-of-rule`,
  addServiceToRule: () => `${SERVER_URL}/add-service-to-rule`,
  removeServiceFromRule: () => `${SERVER_URL}/remove-service-from-rule`,
  updateServiceToRule: () => `${SERVER_URL}/update-service-to-rule`,
  createGroup: () => `${SERVER_URL}/create-group`,
  updateRecipientToGroup: () => `${SERVER_URL}/update-recipient-to-group`,
}
